const hashFunc = require('../util/util');
const Transaction = require('./transaction');

// Block class
class Block {
    constructor (blockHeight, transactions, prevBlockHash) {
        this.nonce = 0;
        this.blockHeight = blockHeight;
        this.timestamp = Date.now();
        this.transactions = transactions;
        this.merkleroot = ''
        this.prevBlockHash = prevBlockHash;
        this.blockHash = '';
    }

    //Method to hash a block
    HashBlock() {
        let blockDataAsString = `${this.blockHeight}${this.nonce}${JSON.stringify(this.transactions)}${this.merkleroot}${this.prevBlockHash}`;
        this.blockHash = hashFunc(blockDataAsString);
        return this.blockHash;
    }

   // Validating if the hash generated by HashBlock() using Proof of Work(PoW);
    ProofOfWork() {
        this.merkleroot = this.CalculateMerkleRoot();
        this.HashBlock();
        while (this.HashBlock().substring(0, 2) !== '00') {
            this.nonce ++;
            this.blockHash = this.HashBlock();
        };
        return this.nonce;
    }

    CalculateMerkleRoot() {
        return hashFunc(`${JSON.stringify(this.transactions)}${this.nonce}`);
    }

    ContainValidTransactions() {
        for (let transaction of this.transactions) {
            if (!(transaction instanceof Transaction)) {
                throw new Error('Invalid transaction instance');
            }
            if (!transaction.IsValidTransaction()) {
                return false;
            }
        }
        return true;
    }
}



module.exports = Block;